# Generated by Django 5.1.4 on 2024-12-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Denis', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(default='qwert', on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.author')),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
